import type { Metadata } from 'next'
import './globals.css'

import Nav from './components/Nav'

export const metadata: Metadata = {
  title: 'Bug Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-row">
        <Nav />
        {children}
      </body>
    </html>
  )
}
