import './globals.css'
import Provider from './Provider'

export const metadata = {
  title: 'Bug Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body>
          {children}
        </body>
      </Provider>
    </html>
  )
}
